### ISSUE TITLE
Issues with JRuby compatibility when using soap4r-ruby1.9

### ISSUE THREAD

**Issue by Hachmaninow** [billgathen/yieldmanager#13]
Hi Bill,

first of all, many thanks for your work on this library! It is very much appreciated. 

We are using the library in jruby-1.7.13 and we already have the soap4r-ruby1.9 dependency in our project and cannot remove it. Unfortunately this seems to be incompatible with the fix that is implemented in lib/yieldmanager/client.rb. 

Another problem concerned the strict dependency to mini_portile vers. 0.6.0.

I have forked your repository and you can have a look at the changes that were necessary to make everything work together: 
https://github.com/adyard/yieldmanager/commit/104303fae304be67d3e650b720279e0eacb97df9

Do you think these changes might be integrated into your version? If there is a chance, I would provide a pull request that includes those changes of course in a compatible way.

Kind regards
Björn Hachmann

**Comment by billgathen** [comment]
Hello Björn!

I'm glad you're finding the library useful, and thank you so much for contributing. :+1: 

The changes look straightforward, though I think leaving .ruby-version alone is probably best: I'll update it to 2.2 the next time I update the API version.

Can you send a pull request on a topic branch? I'll do some testing in the supported C-ruby versions and merge it in if all is well.

Unfortunately, the future of the project is in doubt at the moment, since my company is moving off the Yieldmanager exchange and we won't be using it after the end of January 2015. On the positive side, that would mean I could drop support for 1.8.7 (I have some very old internal apps that haven't been moved up) and eliminate the patching logic entirely, but without a YM account I won't be able to test anymore.

Thanks again for your interest!

**Comment by billgathen** [comment]
Merged and gem pushed! Everything seems to be working on my end and on Travis, so I think you were right about those environment variables being the problem.

Gem version 0.9.13 includes your fixes. They are much-appreciated.

I apologize profusely for how long it took me to get this taken care of. My company has moved away from Yieldmanager and I spend almost all my free time in JavaScript these days.

- Bill
